name: Generate Stats Images

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  github-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: jstrieb/github-stats@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_ACTOR: u-stem

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub stats SVGs"
          file_pattern: "generated/*.svg"
